module.exports = {
  title: ['맥락을 읽는', 'UXer, 이진영입니다'],
  subTitle: '제 최근 작업물을 살펴보세요!',
  projects: [
    {
      name: 'PUDDY',
      mainImage: 'PUDDY.png',
      tags: ['RESEARCH', 'UX/UI', 'APP'],
      title: 'PUDDY : 반려동물의 노후대비를 위한 저축 서비스',
      period: '2021.10 ~ 2022.04',
      images: [
        '0.png',
        '1.png',
        '2.png',
        '3.png',
        '4.png',
        '5.png',
        '6.png',
        '7.png',
        '8.png',
        '9.png',
        '10.png',
        '11.png',
        '12.png',
        '13.png',
        '14.png',
        '15.png',
        '16.png',
        '17.png',
        '18.png',
        '19.png',
        '20.png',
        '21.png',
        '22.png',
      ],
      password: '',
    },
    {
      name: 'myfitbenefit',
      mainImage: 'myfitbenefit.png',
      tags: ['RESEARCH', 'UX/UI', 'APP'],
      title: '사회적 가치소비를 통한 혜택구독서비스',
      period: '2021.04 ~ 2021.05',
      images: [
        'img1.png',
        'img2.png',
        'img3.png',
        'img4.png',
        'img5.png',
        'img6.png',
        'img7.png',
        'img8.png',
        'img9.png',
        'img10.png',
        'img11.png',
      ],
      password: '',
    },
    {
      name: 'findirectshop',
      mainImage: 'findirectshop.png',
      tags: ['RESEARCH', 'UX', 'USABILITY TEST'],
      title: '[Fin Direct Shop] 사용성 개선안 도출 프로젝트',
      period: '2020.12 ~ 2021.02',
      images: [
        'img1.png',
        'img2.png',
        'img3.png',
        'img4.png',
        'img5.png',
        'img6.png',
        'img7.png',
        'img8.png',
        'img9.png',
        'img10.png',
        'img11.png',
      ],
      password: 'qwe123!',
    },
    {
      name: 'at',
      mainImage: 'at.png',
      tags: ['UX/UI', 'APP', 'WEB'],
      title: '빅데이터 기반 못난이농산물 오픈마켓 서비스',
      period: '2020.10 ~ 2020.12',
      images: [
        'img1.png',
        'img2.png',
        'img3.png',
        'img4.png',
        'img5.png',
        'img6.png',
        'img7.png',
        'img8.png',
        'img9.png',
        'img10.png',
        'img11.png',
      ],
      password: '',
    },
    {
      name: 'sugarattack',
      mainImage: 'sugar.png',
      tags: ['APP', 'UX/UI', 'GAME', 'RESEARCH'],
      title: '제1형 당뇨 환아들을 위한 하이브리드 보드게임',
      period: '2020.12 ~ 2020.02',
      images: [
        'img1.png',
        'img2.png',
        'img3.png',
        'img4.png',
        'img5.png',
        'img6.png',
        'img7.png',
        'img8.png',
        'img9.png',
        'img10.png',
      ],
      password: '',
    },
  ],
  modal: {
    title: '공개가 제한된 프로젝트입니다',
    description: '이 프로젝트는 보안 이슈로 인해 암호를 전달받은 분만 보실수 있어요',
    placehoder: '암호를 입력해주세요',
    cancel: '취소',
    confirm: '확인',
  },
}
